package com.example.demo.auth;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.test.context.jdbc.Sql.ExecutionPhase;

@SpringBootTest
@Sql(statements = """
		CREATE TABLE member_account (
		    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		    login_id VARCHAR(50) NOT NULL,
		    password_hash VARCHAR(255) NOT NULL,
		    display_name VARCHAR(100) NOT NULL,
		    email VARCHAR(254) NOT NULL,
		    role VARCHAR(20) NOT NULL,
		    status VARCHAR(20) NOT NULL,
		    failed_login_count INTEGER NOT NULL DEFAULT 0,
		    locked_until TIMESTAMP WITH TIME ZONE,
		    last_login_at TIMESTAMP WITH TIME ZONE,
		    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
		);
		""", executionPhase = ExecutionPhase.BEFORE_TEST_METHOD)
@Sql(statements = "DROP TABLE IF EXISTS member_account;", executionPhase = ExecutionPhase.AFTER_TEST_METHOD)
class AuthIntegrationTests {

	@Autowired
	private AuthService authService;

	@Autowired
	private JdbcTemplate jdbcTemplate;

	@Autowired
	private PasswordEncoder passwordEncoder;

	@BeforeEach
	void insertTestAccount() {
		jdbcTemplate.update("""
				INSERT INTO member_account (
				    login_id, password_hash, display_name, email, role, status
				) VALUES (?, ?, ?, ?, ?, ?)
				""",
				"integration-user",
				passwordEncoder.encode("correct-password"),
				"통합 테스트 사용자",
				"integration@example.com",
				"USER",
				"ACTIVE");
	}

	@Test
	void logsInThroughTheRealMyBatisXmlAndUpdatesTheSuccessRecord() {
		LoginResponse response = authService.login(
				new LoginRequest("INTEGRATION-USER", "correct-password"));

		assertThat(response.loginId()).isEqualTo("integration-user");
		assertThat(response.displayName()).isEqualTo("통합 테스트 사용자");
		assertThat(loginCount()).isZero();
		assertThat(lastLoginWasRecorded()).isTrue();
	}

	@Test
	void commitsTheFailureCountWhenThePasswordIsIncorrect() {
		assertThatThrownBy(() -> authService.login(
				new LoginRequest("integration-user", "wrong-password")))
				.isInstanceOf(UnauthorizedLoginException.class);

		assertThat(loginCount()).isEqualTo(1);
		assertThat(lastLoginWasRecorded()).isFalse();
	}

	@Test
	void signsUpWithAHashAndCanLogInImmediately() {
		SignUpResponse signUpResponse = authService.signUp(new SignUpRequest(
				"new-user",
				"새 사용자",
				"NEW@example.com",
				"new-password"));

		String storedHash = jdbcTemplate.queryForObject(
				"SELECT password_hash FROM member_account WHERE login_id = 'new-user'",
				String.class);

		assertThat(signUpResponse.loginId()).isEqualTo("new-user");
		assertThat(signUpResponse.email()).isEqualTo("new@example.com");
		assertThat(storedHash).isNotEqualTo("new-password");
		assertThat(passwordEncoder.matches("new-password", storedHash)).isTrue();

		LoginResponse loginResponse = authService.login(
				new LoginRequest("new-user", "new-password"));
		assertThat(loginResponse.displayName()).isEqualTo("새 사용자");
	}

	private Integer loginCount() {
		return jdbcTemplate.queryForObject(
				"SELECT failed_login_count FROM member_account WHERE login_id = 'integration-user'",
				Integer.class);
	}

	private Boolean lastLoginWasRecorded() {
		return jdbcTemplate.queryForObject(
				"SELECT last_login_at IS NOT NULL FROM member_account WHERE login_id = 'integration-user'",
				Boolean.class);
	}
}
