CREATE TABLE member_account (
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    failed_login_count INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ,
    email_verified_at TIMESTAMPTZ,
    password_changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_member_account_role
        CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT chk_member_account_status
        CHECK (status IN ('ACTIVE', 'LOCKED', 'DISABLED', 'WITHDRAWN')),
    CONSTRAINT chk_member_account_failed_login_count
        CHECK (failed_login_count >= 0),
    CONSTRAINT chk_member_account_login_id_not_blank
        CHECK (btrim(login_id) <> ''),
    CONSTRAINT chk_member_account_display_name_not_blank
        CHECK (btrim(display_name) <> ''),
    CONSTRAINT chk_member_account_email_not_blank
        CHECK (btrim(email) <> '')
);

CREATE UNIQUE INDEX uq_member_account_login_id_lower
    ON member_account (lower(login_id));

CREATE UNIQUE INDEX uq_member_account_email_lower
    ON member_account (lower(email));

CREATE INDEX idx_member_account_status
    ON member_account (status);

COMMENT ON TABLE member_account IS '로그인과 회원 계정 정보를 저장하는 테이블';
COMMENT ON COLUMN member_account.member_id IS '회원 내부 식별자';
COMMENT ON COLUMN member_account.login_id IS '로그인에 사용하는 고유 아이디';
COMMENT ON COLUMN member_account.password_hash IS 'Argon2id 또는 bcrypt로 생성한 비밀번호 해시';
COMMENT ON COLUMN member_account.display_name IS '화면에 표시할 회원 이름';
COMMENT ON COLUMN member_account.email IS '로그인 알림과 비밀번호 재설정에 사용할 이메일';
COMMENT ON COLUMN member_account.role IS 'USER 또는 ADMIN 권한';
COMMENT ON COLUMN member_account.status IS 'ACTIVE, LOCKED, DISABLED, WITHDRAWN 계정 상태';
COMMENT ON COLUMN member_account.failed_login_count IS '연속 로그인 실패 횟수';
COMMENT ON COLUMN member_account.locked_until IS '계정 잠금 만료 시각';
COMMENT ON COLUMN member_account.last_login_at IS '마지막 로그인 성공 시각';
COMMENT ON COLUMN member_account.email_verified_at IS '이메일 인증 완료 시각';
COMMENT ON COLUMN member_account.password_changed_at IS '마지막 비밀번호 변경 시각';
COMMENT ON COLUMN member_account.created_at IS '계정 생성 시각';
COMMENT ON COLUMN member_account.updated_at IS '계정 최종 수정 시각';
